apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-rabbit
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/dmitry/GeekBrains/4_Semestr/practice/1_conteinerization/lesson_04/my_pv
  storageClassName: local
